In [76]:
import torch
import torch.nn as nn
import numpy as np
from sklearn.metrics import accuracy_score, f1_score
from torchvision.ops import sigmoid_focal_loss
from utils.metrics import metric, classification_metric, FocalLoss

In [77]:
loss = nn.CrossEntropyLoss()
#loss = nn.BCELoss() # Balanced Cross-Entropy Loss # Gives error
#loss = FocalLoss()
#loss = sigmoid_focal_loss()

In [78]:
y_pred = [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
y_true = [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]

In [79]:
#input = torch.randn(3, 5, requires_grad=True)
input = torch.tensor(np.array(y_pred), dtype=torch.float)
input

tensor([1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [80]:
#target = torch.empty(16, dtype=torch.float).random_(5)
target = torch.tensor(np.array(y_true), dtype=torch.float)
target

tensor([1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.])

In [81]:
output = loss(input, target)
output

tensor(26.0203)

In [82]:
accuracy_score(y_true, y_pred)

0.875

In [83]:
f1_score(y_true, y_pred, average='macro')

0.8666666666666667

In [85]:
input_3d = torch.randn(16, 2)
input_3d

tensor([[ 1.1356,  1.3014, -0.7461, -0.6436, -2.0175],
        [-2.9922,  0.9163,  0.1632, -0.7879, -0.0825],
        [ 0.0640, -0.5574, -0.7832, -0.1919,  0.4926]])

In [86]:
values, indices = torch.max(input_3d, dim=1, keepdim=True)

In [87]:
values

tensor([[1.3014],
        [0.9163],
        [0.4926]])

In [88]:
indices

tensor([[1],
        [1],
        [4]])